api_platform:
    title: Pole Dance App API
    version: 1.0.0
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
    error_formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json', 'application/problem+json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_enabled: true
        pagination_items_per_page: 30
        pagination_maximum_items_per_page: 100
        pagination_client_items_per_page: true
    openapi:
        contact:
            name: Pole Dance App

