framework:
    rate_limiter:
        login:
            policy: fixed_window
            limit: 5
            interval: '1 minute'
        register:
            policy: fixed_window
            limit: 3
            interval: '1 hour'
