---
# Production environment override
# Usage : docker compose -f compose.yaml -f compose.prod.yaml up -d
services:

  # Adminer désactivé en production
  adminer:
    profiles:
      - dev

  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    restart: unless-stopped

  database:
    restart: unless-stopped
