<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327152029 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE skill_media_tuto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) DEFAULT NULL, mimetype VARCHAR(100) NOT NULL, original_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, skill_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D7B381F65585C142 ON skill_media_tuto (skill_id)');
        $this->addSql('CREATE INDEX IDX_D7B381F6B03A8386 ON skill_media_tuto (created_by_id)');
        $this->addSql('ALTER TABLE skill_media_tuto ADD CONSTRAINT FK_D7B381F65585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE skill_media_tuto ADD CONSTRAINT FK_D7B381F6B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE skill_media_tuto DROP CONSTRAINT FK_D7B381F65585C142');
        $this->addSql('ALTER TABLE skill_media_tuto DROP CONSTRAINT FK_D7B381F6B03A8386');
        $this->addSql('DROP TABLE skill_media_tuto');
    }
}
