<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260401224635 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) DEFAULT NULL, mimetype VARCHAR(100) DEFAULT NULL, original_name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, activity_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_742E97BF81C06096 ON activity_media (activity_id)');
        $this->addSql('CREATE INDEX IDX_742E97BFB03A8386 ON activity_media (created_by_id)');
        $this->addSql('CREATE TABLE activity_type_media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_path VARCHAR(255) DEFAULT NULL, mimetype VARCHAR(100) DEFAULT NULL, original_name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, activity_type_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_31C218F3C51EFA73 ON activity_type_media (activity_type_id)');
        $this->addSql('CREATE INDEX IDX_31C218F3B03A8386 ON activity_type_media (created_by_id)');
        $this->addSql('ALTER TABLE activity_media ADD CONSTRAINT FK_742E97BF81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_media ADD CONSTRAINT FK_742E97BFB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_type_media ADD CONSTRAINT FK_31C218F3C51EFA73 FOREIGN KEY (activity_type_id) REFERENCES activity_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_type_media ADD CONSTRAINT FK_31C218F3B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_media DROP CONSTRAINT FK_742E97BF81C06096');
        $this->addSql('ALTER TABLE activity_media DROP CONSTRAINT FK_742E97BFB03A8386');
        $this->addSql('ALTER TABLE activity_type_media DROP CONSTRAINT FK_31C218F3C51EFA73');
        $this->addSql('ALTER TABLE activity_type_media DROP CONSTRAINT FK_31C218F3B03A8386');
        $this->addSql('DROP TABLE activity_media');
        $this->addSql('DROP TABLE activity_type_media');
    }
}
