<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260313085139 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notif_type VARCHAR(50) NOT NULL, subject_type VARCHAR(30) DEFAULT NULL, subject_id INT DEFAULT NULL, context JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, triggered_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD1AEF5E63C5923F ON notification_event (triggered_by_id)');
        $this->addSql('CREATE TABLE notification_receipt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_read BOOLEAN NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id INT NOT NULL, recipient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_46873CF271F7E88B ON notification_receipt (event_id)');
        $this->addSql('CREATE INDEX IDX_46873CF2E92F8F78 ON notification_receipt (recipient_id)');
        $this->addSql('ALTER TABLE notification_event ADD CONSTRAINT FK_FD1AEF5E63C5923F FOREIGN KEY (triggered_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE notification_receipt ADD CONSTRAINT FK_46873CF271F7E88B FOREIGN KEY (event_id) REFERENCES notification_event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification_receipt ADD CONSTRAINT FK_46873CF2E92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT fk_bf5476cae92f8f78');
        $this->addSql('DROP TABLE notification');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notif_type VARCHAR(50) NOT NULL, message TEXT NOT NULL, is_read BOOLEAN NOT NULL, subject_type VARCHAR(50) DEFAULT NULL, subject_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, context JSON DEFAULT NULL, recipient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_bf5476cae92f8f78 ON notification (recipient_id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT fk_bf5476cae92f8f78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_event DROP CONSTRAINT FK_FD1AEF5E63C5923F');
        $this->addSql('ALTER TABLE notification_receipt DROP CONSTRAINT FK_46873CF271F7E88B');
        $this->addSql('ALTER TABLE notification_receipt DROP CONSTRAINT FK_46873CF2E92F8F78');
        $this->addSql('DROP TABLE notification_event');
        $this->addSql('DROP TABLE notification_receipt');
    }
}
